### ISSUE TITLE
Cats-effect module

### ISSUE THREAD

**Issue by Slakah** [alexarchambault/case-app#200]
Thanks for the fantastic library @alexarchambault , we've been using this quite a bit internally. Is there any appetite to add a `case-app-cats` module, the code to support this would look roughly like https://gist.github.com/Slakah/9b905b0fd20b715c28862da913ff73c5 .

In effect `IOCaseApp` and `IOCommandApp` leverage `IOApp` to provide the `override def run(args: List[String]): IO[ExitCode]`.

**Comment by alexarchambault** [comment]
@Slakah That would be great, go ahead!

**Comment by Slakah** [comment]
Implemented by #202
