### ISSUE TITLE
Site

### ISSUE THREAD

**Issue by Slakah** [alexarchambault/case-app#203]
While adding documentation for https://github.com/alexarchambault/case-app/pull/202 . I started thinking the `README.md` could be getting a touch large at this point.

The the docusaurus stuff from coursier could be reused here to produce a doc site https://github.com/coursier/coursier/blob/b08cd47ef2b5f2c269b97d32a36228dc4f94ba02/doc/docs/dev-website.md .

**Comment by alexarchambault** [comment]
Agreed, I just didn't take the time to do it. [sbt-microsites](https://github.com/47degrees/sbt-microsites) could work too. PR welcome!

**Comment by regadas** [comment]
Another alternative that you can consider is [paradox](https://github.com/lightbend/paradox) with [material](https://github.com/jonas/paradox-material-theme). I tend to use these since they don't require any additional tools.

**Comment by Slakah** [comment]
@regadas , I hadn't seen the material theme for paradox before, the layout looks much more user friendly. I'd still be tempted to use docusaurus though, as it's what I see a lot of Scala projects using instead of sbt-microsites, and I'm a sucker for following the herd.

**Comment by alexarchambault** [comment]
Fixed by https://github.com/alexarchambault/case-app/pull/550
