### ISSUE TITLE
zsh completion on a new shell

### ISSUE THREAD

**Issue by kiendang** [alexarchambault/case-app#413]
Very tiny issue with zsh completion.

I'm not sure what `typeset -A opt_args` does here 

https://github.com/alexarchambault/case-app/blob/fbeaa6bc4fafdd82830e16676873e3d479746d38/core/shared/src/main/scala/caseapp/core/complete/Zsh.scala#L12-L19

but with it, on a new shell, I always need to hit tab twice for the first completion to work, *e.g.* try `scala-cli re|` on a new shell, but after that everything works normally. After taking out that line the first completion on a new shell works on the first tab. Tested with scala-cli on Arch Linux and Mac OS (intel), zsh 5.9.

**Comment by alexarchambault** [comment]
> with it, on a new shell, I always need to hit tab twice for the first completion to work

I'm getting that too. I can't recall right now why I added that line...

**Comment by alexarchambault** [comment]
And it seems removing it doesn't break anything in a few manual checks I just tried... :thinking:
