### ISSUE TITLE
Compatibility with Scala native

### ISSUE THREAD

**Issue by schrepfler** [alexarchambault/case-app#62]
Scala-native can really use a nice command line argument parsing library like case-app.

**Comment by alexarchambault** [comment]
I'm 100% for this :-)

https://github.com/milessabin/shapeless/pull/727 and https://github.com/alexarchambault/case-app/commit/a18ab2eed604392560e7b70e38eea29912fe58d4 are first steps in that direction.

**Comment by alexarchambault** [comment]
`1.2.0-M4` with scala-native support is out!
