### ISSUE TITLE
shapeless for Scala > 2.10 no longer depends on macro-compat

### ISSUE THREAD

**Issue by milessabin** [alexarchambault/case-app#87]
As of [this commit](https://github.com/milessabin/shapeless/commit/ab5a1a6bb1e01e13fd417e0ee0d8726d54344d84) shapeless no longer depends on macro-compat for Scala > 2.10, instead it provides [a local definition](https://github.com/milessabin/shapeless/blob/master/core/src/main/scala_2.13-/shapeless/versionspecifics.scala#L47-L49) of `macrocompat.bundle` to preserve source compatibility for later Scala versions.

Unfortunately this interferes with case-app's extension of `CaseClassMacros` in `AnnotationListMacros`, as [discovered](https://github.com/milessabin/shapeless/issues/849) by @SethTisue in the 2.12.x community build.

I suggest making a similar change here: provide a local definition of `macrocompat.bundle` which is only used for Scala > 2.10.

At some point in the next year or two shapeless will drop 2.10 support, at which point the macro-compat dependency will go away altogether. If case-app drops 2.10 support now it could immediately drop the macro-compat dependency which would also solve this issue.

**Comment by alexarchambault** [comment]
Thanks for the heads up! I answered directly on https://github.com/milessabin/shapeless/issues/849.

**Comment by alexarchambault** [comment]
Should be fixed by https://github.com/alexarchambault/case-app/pull/89.
